### ISSUE TITLE
Add info with MCPatcher

### ISSUE THREAD

**Issue by HowardZHY** [DeexCoding/SaltLib#5]
![2022-09-17_22 26 37](https://user-images.githubusercontent.com/96782166/190862159-a8582e04-55c2-4a53-87ae-f11dc1c972ee.png)
I suggest to add "If u want some Optifine features, install MCPatcher(without Extended HD) before install fabric." to readme
MCPatcher almost works fine, but Extend HD have 20 fps performance bug so don't install.

**Comment by DeexCoding** [comment]
SaltLib is not and was never meant to be compatible with OptiFine, if someone wants to have OptiFine features with SaltLib's performance boost they can do it with MCPatcher, however it's not my job to instruct them on how to do it.

**Comment by DeexCoding** [comment]
SaltLib is not and was never meant to be compatible with OptiFine, if someone wants to have OptiFine features with SaltLib's performance boost they can do it with MCPatcher, however it's not my job to instruct them on how to do it.
